/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sendMessageSameChainSol from "./sendMessageSameChain.sol";
export type { sendMessageSameChainSol };
