/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RPSGame__factory } from "./RPSGame__factory";
export { RPSServer__factory } from "./RPSServer__factory";
