/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as auctionFactorySol from "./AuctionFactory.sol";
export * as auxiliarContracts from "./auxiliarContracts";
export * as zkVickreyAuctionSol from "./zkVickreyAuction.sol";
