/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tokenBridgeSol from "./TokenBridge.sol";
export type { tokenBridgeSol };
export type { TokenA } from "./TokenA";
export type { TokenB } from "./TokenB";
