/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenCrosschain from "./ERC20-Token-crosschain";
export type { erc20TokenCrosschain };
import type * as erc20TokenSamechain from "./ERC20-Token-samechain";
export type { erc20TokenSamechain };
import type * as nftSamechain from "./NFT-samechain";
export type { nftSamechain };
import type * as airdrop from "./airdrop";
export type { airdrop };
import type * as callContract from "./call-contract";
export type { callContract };
import type * as callContractWithToken from "./call-contract-with-token";
export type { callContractWithToken };
import type * as crossChainZkp from "./cross-chain-zkp";
export type { crossChainZkp };
import type * as marketplaceSamechain from "./marketplace-samechain";
export type { marketplaceSamechain };
import type * as nftLinker from "./nft-linker";
export type { nftLinker };
import type * as rockPappgerScissor from "./rock-pappger-scissor";
export type { rockPappgerScissor };
import type * as sendMessage from "./sendMessage";
export type { sendMessage };
import type * as sendMessageCrossChain from "./sendMessageCrossChain";
export type { sendMessageCrossChain };
import type * as sendMessageSameChain from "./sendMessageSameChain";
export type { sendMessageSameChain };
import type * as sendMessageSameChainSol from "./sendMessageSameChain.sol";
export type { sendMessageSameChainSol };
import type * as zkpSamechain from "./zkp-samechain";
export type { zkpSamechain };
