/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface RPSGameInterface extends utils.Interface {
  functions: {
    "addInitiatorChoice(uint8,string)": FunctionFragment;
    "addResponderChoice(uint8,string)": FunctionFragment;
    "addResponse(bytes32)": FunctionFragment;
    "getResult()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addInitiatorChoice"
      | "addResponderChoice"
      | "addResponse"
      | "getResult"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addInitiatorChoice",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addResponderChoice",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addResponse",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "getResult", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addInitiatorChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addResponderChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;

  events: {};
}

export interface RPSGame extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RPSGameInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addInitiatorChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addResponderChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addResponse(
      _responder_hash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getResult(overrides?: CallOverrides): Promise<[string, number, string]>;
  };

  addInitiatorChoice(
    _choice: PromiseOrValue<BigNumberish>,
    _randomStr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addResponderChoice(
    _choice: PromiseOrValue<BigNumberish>,
    _randomStr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addResponse(
    _responder_hash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getResult(overrides?: CallOverrides): Promise<[string, number, string]>;

  callStatic: {
    addInitiatorChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addResponderChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    addResponse(
      _responder_hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getResult(overrides?: CallOverrides): Promise<[string, number, string]>;
  };

  filters: {};

  estimateGas: {
    addInitiatorChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addResponderChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addResponse(
      _responder_hash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getResult(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addInitiatorChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addResponderChoice(
      _choice: PromiseOrValue<BigNumberish>,
      _randomStr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addResponse(
      _responder_hash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getResult(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
