/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface SumsToFifteenInterface extends utils.Interface {
  functions: {
    "success()": FunctionFragment;
    "verifyFifteen(uint256[2],uint256[2],uint256[2][2],uint256[2],uint256[2],uint256[2],uint256[2],uint256[2],uint256[2])": FunctionFragment;
    "verifyTx(uint256[2],uint256[2],uint256[2][2],uint256[2],uint256[2],uint256[2],uint256[2],uint256[2],uint256[2])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "success" | "verifyFifteen" | "verifyTx"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "success", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyFifteen",
    values: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTx",
    values: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "success", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyFifteen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifyTx", data: BytesLike): Result;

  events: {
    "Verified(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Verified"): EventFragment;
}

export interface VerifiedEventObject {
  arg0: string;
}
export type VerifiedEvent = TypedEvent<[string], VerifiedEventObject>;

export type VerifiedEventFilter = TypedEventFilter<VerifiedEvent>;

export interface SumsToFifteen extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SumsToFifteenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    success(overrides?: CallOverrides): Promise<[boolean]>;

    verifyFifteen(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyTx(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  success(overrides?: CallOverrides): Promise<boolean>;

  verifyFifteen(
    a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    b: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ],
    b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyTx(
    a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    b: [
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ],
    b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    success(overrides?: CallOverrides): Promise<boolean>;

    verifyFifteen(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<void>;

    verifyTx(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "Verified(string)"(arg0?: null): VerifiedEventFilter;
    Verified(arg0?: null): VerifiedEventFilter;
  };

  estimateGas: {
    success(overrides?: CallOverrides): Promise<BigNumber>;

    verifyFifteen(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyTx(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    success(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verifyFifteen(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyTx(
      a: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      a_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      b: [
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
        [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
      ],
      b_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      c_p: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      h: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      k: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      input: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
