/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionFactorySol from "./AuctionFactory.sol";
export type { auctionFactorySol };
import type * as auxiliarContracts from "./auxiliarContracts";
export type { auxiliarContracts };
import type * as zkVickreyAuctionSol from "./zkVickreyAuction.sol";
export type { zkVickreyAuctionSol };
