/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vickreyAuctionSol from "./VickreyAuction.sol";
export type { vickreyAuctionSol };
import type * as atomicSwap from "./atomic-swap";
export type { atomicSwap };
import type * as pedersenCommitment from "./pedersen-commitment";
export type { pedersenCommitment };
import type * as pedersenCommitments from "./pedersen-commitments";
export type { pedersenCommitments };
import type * as sctSol from "./sct.sol";
export type { sctSol };
import type * as zkSnarKs from "./zkSNARKs";
export type { zkSnarKs };
export type { BridgeA } from "./BridgeA";
export type { BridgeB } from "./BridgeB";
export type { Storage } from "./Storage";
export type { TokenA } from "./TokenA";
export type { TokenB } from "./TokenB";
