/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zkp from "./ZKP";
export type { zkp };
export type { ContestContract } from "./ContestContract";
export type { Migrations } from "./Migrations";
