/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../../common";

export interface ECToolsInterface extends utils.Interface {
  functions: {
    "Gx()": FunctionFragment;
    "Gy()": FunctionFragment;
    "Hx()": FunctionFragment;
    "Hy()": FunctionFragment;
    "a()": FunctionFragment;
    "b()": FunctionFragment;
    "h1()": FunctionFragment;
    "n()": FunctionFragment;
    "p()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "Gx"
      | "Gy"
      | "Hx"
      | "Hy"
      | "a"
      | "b"
      | "h1"
      | "n"
      | "p"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "Gx", values?: undefined): string;
  encodeFunctionData(functionFragment: "Gy", values?: undefined): string;
  encodeFunctionData(functionFragment: "Hx", values?: undefined): string;
  encodeFunctionData(functionFragment: "Hy", values?: undefined): string;
  encodeFunctionData(functionFragment: "a", values?: undefined): string;
  encodeFunctionData(functionFragment: "b", values?: undefined): string;
  encodeFunctionData(functionFragment: "h1", values?: undefined): string;
  encodeFunctionData(functionFragment: "n", values?: undefined): string;
  encodeFunctionData(functionFragment: "p", values?: undefined): string;

  decodeFunctionResult(functionFragment: "Gx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Gy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Hx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Hy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "a", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "b", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "h1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "n", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "p", data: BytesLike): Result;

  events: {};
}

export interface ECTools extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ECToolsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    Gx(overrides?: CallOverrides): Promise<[BigNumber]>;

    Gy(overrides?: CallOverrides): Promise<[BigNumber]>;

    Hx(overrides?: CallOverrides): Promise<[BigNumber]>;

    Hy(overrides?: CallOverrides): Promise<[BigNumber]>;

    a(overrides?: CallOverrides): Promise<[BigNumber]>;

    b(overrides?: CallOverrides): Promise<[BigNumber]>;

    h1(overrides?: CallOverrides): Promise<[BigNumber]>;

    n(overrides?: CallOverrides): Promise<[BigNumber]>;

    p(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  Gx(overrides?: CallOverrides): Promise<BigNumber>;

  Gy(overrides?: CallOverrides): Promise<BigNumber>;

  Hx(overrides?: CallOverrides): Promise<BigNumber>;

  Hy(overrides?: CallOverrides): Promise<BigNumber>;

  a(overrides?: CallOverrides): Promise<BigNumber>;

  b(overrides?: CallOverrides): Promise<BigNumber>;

  h1(overrides?: CallOverrides): Promise<BigNumber>;

  n(overrides?: CallOverrides): Promise<BigNumber>;

  p(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    Gx(overrides?: CallOverrides): Promise<BigNumber>;

    Gy(overrides?: CallOverrides): Promise<BigNumber>;

    Hx(overrides?: CallOverrides): Promise<BigNumber>;

    Hy(overrides?: CallOverrides): Promise<BigNumber>;

    a(overrides?: CallOverrides): Promise<BigNumber>;

    b(overrides?: CallOverrides): Promise<BigNumber>;

    h1(overrides?: CallOverrides): Promise<BigNumber>;

    n(overrides?: CallOverrides): Promise<BigNumber>;

    p(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    Gx(overrides?: CallOverrides): Promise<BigNumber>;

    Gy(overrides?: CallOverrides): Promise<BigNumber>;

    Hx(overrides?: CallOverrides): Promise<BigNumber>;

    Hy(overrides?: CallOverrides): Promise<BigNumber>;

    a(overrides?: CallOverrides): Promise<BigNumber>;

    b(overrides?: CallOverrides): Promise<BigNumber>;

    h1(overrides?: CallOverrides): Promise<BigNumber>;

    n(overrides?: CallOverrides): Promise<BigNumber>;

    p(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    Gx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    Gy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    Hx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    Hy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    a(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    b(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    h1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    n(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    p(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
