/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Implementation,
  ImplementationInterface,
} from "../../../../../@axelar-network/axelar-gmp-sdk-solidity/contracts/upgradable/Implementation";

const _abi = [
  {
    inputs: [],
    name: "NotProxy",
    type: "error",
  },
  {
    inputs: [],
    name: "contractId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "setup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Implementation__factory {
  static readonly abi = _abi;
  static createInterface(): ImplementationInterface {
    return new utils.Interface(_abi) as ImplementationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Implementation {
    return new Contract(address, _abi, signerOrProvider) as Implementation;
  }
}
