/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITokenB__factory } from "./ITokenB__factory";
export { TokenBridge__factory } from "./TokenBridge__factory";
