/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as elipticCurveToolsSol from "./ElipticCurveTools.sol";
export type { elipticCurveToolsSol };
export type { AuctionObjectToken } from "./AuctionObjectToken";
