/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tokenBridgeSol from "./TokenBridge.sol";
export { TokenA__factory } from "./TokenA__factory";
export { TokenB__factory } from "./TokenB__factory";
