/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ellipticCurveInerfaceSol from "./EllipticCurveInerface.sol";
export type { ellipticCurveInerfaceSol };
export type { EllipticCurve } from "./EllipticCurve";
export type { PedersenContract } from "./PedersenContract";
