/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface PedersenContractInterface extends utils.Interface {
  functions: {
    "gx()": FunctionFragment;
    "invMod(uint256,uint256)": FunctionFragment;
    "gy()": FunctionFragment;
    "eSub(uint256,uint256,uint256,uint256)": FunctionFragment;
    "subCommitment(uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "commit(uint256,uint256)": FunctionFragment;
    "eMul(uint256,uint256,uint256)": FunctionFragment;
    "H()": FunctionFragment;
    "nn()": FunctionFragment;
    "eAdd(uint256,uint256,uint256,uint256)": FunctionFragment;
    "pp()": FunctionFragment;
    "addCommitment(uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "params()": FunctionFragment;
    "verify(uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "gx"
      | "invMod"
      | "gy"
      | "eSub"
      | "subCommitment"
      | "commit"
      | "eMul"
      | "H"
      | "nn"
      | "eAdd"
      | "pp"
      | "addCommitment"
      | "params"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "gx", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "invMod",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "gy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eSub",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "subCommitment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "commit",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "eMul",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "H", values?: undefined): string;
  encodeFunctionData(functionFragment: "nn", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eAdd",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "pp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addCommitment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "params", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "gx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "invMod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eSub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "H", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "params", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface PedersenContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PedersenContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    gx(overrides?: CallOverrides): Promise<[BigNumber]>;

    invMod(
      x: PromiseOrValue<BigNumberish>,
      pp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { q: BigNumber }>;

    gy(overrides?: CallOverrides): Promise<[BigNumber]>;

    eSub(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

    subCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        _r3: BigNumber;
        _x3: BigNumber;
        _y3: BigNumber;
      }
    >;

    commit(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

    eMul(
      _z: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x2: BigNumber; _y2: BigNumber }>;

    H(overrides?: CallOverrides): Promise<[BigNumber]>;

    nn(overrides?: CallOverrides): Promise<[BigNumber]>;

    eAdd(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

    pp(overrides?: CallOverrides): Promise<[BigNumber]>;

    addCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        _r3: BigNumber;
        _x3: BigNumber;
        _y3: BigNumber;
      }
    >;

    params(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _h: BigNumber;
        _pp: BigNumber;
        _nn: BigNumber;
        _gx: BigNumber;
        _gy: BigNumber;
      }
    >;

    verify(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { result: boolean }>;
  };

  gx(overrides?: CallOverrides): Promise<BigNumber>;

  invMod(
    x: PromiseOrValue<BigNumberish>,
    pp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  gy(overrides?: CallOverrides): Promise<BigNumber>;

  eSub(
    _x1: PromiseOrValue<BigNumberish>,
    _y1: PromiseOrValue<BigNumberish>,
    _x2: PromiseOrValue<BigNumberish>,
    _y2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

  subCommitment(
    _r1: PromiseOrValue<BigNumberish>,
    _x1: PromiseOrValue<BigNumberish>,
    _y1: PromiseOrValue<BigNumberish>,
    _r2: PromiseOrValue<BigNumberish>,
    _x2: PromiseOrValue<BigNumberish>,
    _y2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      _r3: BigNumber;
      _x3: BigNumber;
      _y3: BigNumber;
    }
  >;

  commit(
    _r: PromiseOrValue<BigNumberish>,
    _v: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

  eMul(
    _z: PromiseOrValue<BigNumberish>,
    _x1: PromiseOrValue<BigNumberish>,
    _y1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _x2: BigNumber; _y2: BigNumber }>;

  H(overrides?: CallOverrides): Promise<BigNumber>;

  nn(overrides?: CallOverrides): Promise<BigNumber>;

  eAdd(
    _x1: PromiseOrValue<BigNumberish>,
    _y1: PromiseOrValue<BigNumberish>,
    _x2: PromiseOrValue<BigNumberish>,
    _y2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

  pp(overrides?: CallOverrides): Promise<BigNumber>;

  addCommitment(
    _r1: PromiseOrValue<BigNumberish>,
    _x1: PromiseOrValue<BigNumberish>,
    _y1: PromiseOrValue<BigNumberish>,
    _r2: PromiseOrValue<BigNumberish>,
    _x2: PromiseOrValue<BigNumberish>,
    _y2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      _r3: BigNumber;
      _x3: BigNumber;
      _y3: BigNumber;
    }
  >;

  params(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      _h: BigNumber;
      _pp: BigNumber;
      _nn: BigNumber;
      _gx: BigNumber;
      _gy: BigNumber;
    }
  >;

  verify(
    _r: PromiseOrValue<BigNumberish>,
    _v: PromiseOrValue<BigNumberish>,
    _x1: PromiseOrValue<BigNumberish>,
    _y1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    gx(overrides?: CallOverrides): Promise<BigNumber>;

    invMod(
      x: PromiseOrValue<BigNumberish>,
      pp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gy(overrides?: CallOverrides): Promise<BigNumber>;

    eSub(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

    subCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        _r3: BigNumber;
        _x3: BigNumber;
        _y3: BigNumber;
      }
    >;

    commit(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

    eMul(
      _z: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x2: BigNumber; _y2: BigNumber }>;

    H(overrides?: CallOverrides): Promise<BigNumber>;

    nn(overrides?: CallOverrides): Promise<BigNumber>;

    eAdd(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { _x3: BigNumber; _y3: BigNumber }>;

    pp(overrides?: CallOverrides): Promise<BigNumber>;

    addCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        _r3: BigNumber;
        _x3: BigNumber;
        _y3: BigNumber;
      }
    >;

    params(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        _h: BigNumber;
        _pp: BigNumber;
        _nn: BigNumber;
        _gx: BigNumber;
        _gy: BigNumber;
      }
    >;

    verify(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    gx(overrides?: CallOverrides): Promise<BigNumber>;

    invMod(
      x: PromiseOrValue<BigNumberish>,
      pp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gy(overrides?: CallOverrides): Promise<BigNumber>;

    eSub(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    subCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    commit(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    eMul(
      _z: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    H(overrides?: CallOverrides): Promise<BigNumber>;

    nn(overrides?: CallOverrides): Promise<BigNumber>;

    eAdd(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pp(overrides?: CallOverrides): Promise<BigNumber>;

    addCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    params(overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    gx(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    invMod(
      x: PromiseOrValue<BigNumberish>,
      pp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eSub(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    subCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    commit(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    eMul(
      _z: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    H(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nn(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eAdd(
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addCommitment(
      _r1: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      _x2: PromiseOrValue<BigNumberish>,
      _y2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    params(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verify(
      _r: PromiseOrValue<BigNumberish>,
      _v: PromiseOrValue<BigNumberish>,
      _x1: PromiseOrValue<BigNumberish>,
      _y1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
