/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rockPaperScissorsSol from "./Rock_Paper_Scissors.sol";
export type { rockPaperScissorsSol };
